#!/usr/bin/env bash
# Maugood pilot — first-boot bootstrap on the Omran (or any pilot) host.
#
# What it does:
#   1. Generates fresh secrets (Fernet key, session secret, DB passwords)
#      using only Python 3 stdlib so we don't need pip-installed deps on
#      the target host.
#   2. Writes ./.env with MAUGOOD_ENV=production (the dev-only /api/_test/*
#      endpoints will NOT mount).
#   3. Prints the generated values ONCE so the operator can paste them
#      into Omran's secret manager. Re-running the script will not
#      regenerate (the existing .env is treated as authoritative).
#   4. Prompts before bringing up the stack — never starts containers
#      without explicit confirmation.
#
# Run from the repo root:
#   ./scripts/omran_bootstrap.sh
#
# Pilot scope only — production hardening (real cert, rotation, vault
# integration) is a v1.0 concern.

set -euo pipefail

# Resolve repo root from the script's location so the operator can run
# this from anywhere.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

cd "$REPO_ROOT"

ENV_FILE="$REPO_ROOT/.env"

if [[ -f "$ENV_FILE" ]]; then
  echo "Refusing to overwrite existing $ENV_FILE."
  echo
  echo "If you intentionally want to regenerate secrets, move the existing"
  echo "file out of the way first (e.g. mv .env .env.bak) and re-run."
  echo "Note: regenerating MAUGOOD_FERNET_KEY makes every previously-encrypted"
  echo "      face crop, capture crop, RTSP URL, and embedding unreadable."
  exit 1
fi

if ! command -v python3 >/dev/null 2>&1; then
  echo "python3 not found on PATH — aborting."
  echo "On Ubuntu 22.04: apt-get install -y python3"
  exit 1
fi

if ! command -v docker >/dev/null 2>&1; then
  echo "docker not found on PATH — aborting."
  echo "Follow Docker's official Ubuntu install guide before re-running."
  exit 1
fi

if ! docker compose version >/dev/null 2>&1; then
  echo "docker compose v2 plugin not found — aborting."
  echo "Install via 'apt-get install docker-compose-plugin' or follow Docker's docs."
  exit 1
fi

# --- Generate secrets ------------------------------------------------------
# Fernet keys are urlsafe-base64-encoded 32 random bytes; doing it via
# secrets + base64 stays in stdlib so we don't need cryptography on the host.
FERNET_KEY="$(python3 -c 'import base64,secrets;print(base64.urlsafe_b64encode(secrets.token_bytes(32)).decode())')"
SESSION_SECRET="$(python3 -c 'import secrets;print(secrets.token_urlsafe(48))')"
DB_APP_PW="$(python3 -c 'import secrets;print(secrets.token_urlsafe(24))')"
DB_ADMIN_PW="$(python3 -c 'import secrets;print(secrets.token_urlsafe(24))')"

# --- Write .env ------------------------------------------------------------
cat > "$ENV_FILE" <<EOF
# Generated by scripts/omran_bootstrap.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Pilot deployment for the Omran on-site demo.
# DO NOT commit this file. DO record MAUGOOD_FERNET_KEY in Omran's
# secret manager — losing it makes every encrypted artifact unrecoverable.

MAUGOOD_ENV=production
MAUGOOD_TENANT_MODE=single

MAUGOOD_DATABASE_URL=postgresql+psycopg://maugood_app:${DB_APP_PW}@postgres:5432/maugood
MAUGOOD_ADMIN_DATABASE_URL=postgresql+psycopg://maugood:maugood@postgres:5432/maugood
MAUGOOD_APP_DB_PASSWORD=${DB_APP_PW}
MAUGOOD_ADMIN_DB_PASSWORD=${DB_ADMIN_PW}

MAUGOOD_SESSION_SECRET=${SESSION_SECRET}
MAUGOOD_FERNET_KEY=${FERNET_KEY}

# Pilot defaults — adjust if Omran's HR contact wants different values.
MAUGOOD_LOCAL_TIMEZONE=Asia/Muscat
MAUGOOD_SESSION_IDLE_MINUTES=60
MAUGOOD_LOGIN_MAX_ATTEMPTS=10
MAUGOOD_LOGIN_RATE_LIMIT_RESET_MINUTES=10
MAUGOOD_MATCH_THRESHOLD=0.45
MAUGOOD_ATTENDANCE_RECOMPUTE_MINUTES=15
EOF
chmod 600 "$ENV_FILE"

# --- Print once for the operator -------------------------------------------
cat <<EOF

================================================================
PILOT SECRETS — record these in Omran's secret manager NOW.
This is the only time this script will print them.
================================================================

  MAUGOOD_FERNET_KEY      = ${FERNET_KEY}
  MAUGOOD_SESSION_SECRET  = ${SESSION_SECRET}
  MAUGOOD_APP_DB_PASSWORD = ${DB_APP_PW}
  MAUGOOD_ADMIN_DB_PASSWORD = ${DB_ADMIN_PW}

Saved to: ${ENV_FILE} (mode 600)

Press <Enter> after you have copied them into Omran's secret manager.
================================================================
EOF

read -r -p "" _

# --- Confirm before bringing up the stack ----------------------------------
cat <<EOF

Ready to:
  1. docker compose up -d --build
  2. Tail backend logs until you see 'Application startup complete'.
  3. Hand off to scripts.seed_admin to create the first Admin user.

Bring up the stack now? [y/N] EOF
read -r CONFIRM
case "$CONFIRM" in
  y|Y|yes|YES)
    echo
    echo "Building and starting…"
    docker compose up -d --build
    echo
    echo "Waiting 15s for migrations + capture manager to settle…"
    sleep 15
    echo
    echo "Backend health check:"
    if curl -sS -o /dev/null -w "  HTTP %{http_code}\n" http://localhost:8000/api/health; then
      :
    fi
    echo
    echo "Next steps:"
    echo "  1. docker compose exec -e MAUGOOD_SEED_PASSWORD='...' backend \\"
    echo "     python -m scripts.seed_admin --email <hr-contact@omran> --full-name '...'"
    echo "  2. Sign in at http://localhost:5173 and add cameras."
    echo "  3. Continue with docs/pilot-day-runbook.md."
    ;;
  *)
    echo
    echo "Stack NOT started. When ready, run: docker compose up -d --build"
    ;;
esac
